package com.xyxj.robot.dingding

/**
 * created by ixyxj on 2018/6/21 10:21
 * Copyright (c) 2018 in FORETREE
 */
enum class PackageEnum(val packageName: String) {
    teamviewer("com.teamviewer.quicksupport.market"),
    instagram("com.instagram.android"),
    facebook("com.facebook.katana"),
    messenger("com.facebook.orca"),
    whatsapp("com.whatsapp"),
    gmail("com.google.android.gm"),
    googlemap("com.google.android.apps.maps"),
    allo("com.google.android.apps.fireball"),
    takeoutnew("com.sankuai.meituan.takeoutnew"),
    ele("me.ele"),
    mobikeapp("com.mobike.mobikeapp"),
    labofo("so.ofo.labofo"),
    articlenews("com.ss.android.article.news"),
    weibo("com.sina.weibo"),
    newsreader("com.netease.newsreader.activity"),
    gifmaker("com.smile.gifmaker"),
    zhihu("com.zhihu.android"),
    kiwi("com.duowan.kiwi"),
    ingkee("com.meelive.ingkee"),
    videoeditor("com.yixia.videoeditor"),
    mtxx("com.mt.mtxx.mtxx"),
    meiyancamera("com.meitu.meiyancamera"),
    ctrip("ctrip.android.view"),
    momo("com.immomo.momo"),
    youku("com.youku.phone"),
    qiyi("com.qiyi.video"),
    didi("com.sdu.didi.psnger"),
    AlipayGphone("com.eg.android.AlipayGphone"),
    taobao("com.taobao.taobao"),
    jingdong("com.jingdong.app.mall"),
    dianping("com.dianping.v1"),
    sogou("com.sohu.inputmethod.sogou"),
    BaiduMap("com.baidu.BaiduMap"),
    autonavi("com.autonavi.minimap"),
    jianshu("com.jianshu.haruki"),
    dedao("com.luojilab.player"),
    ximalaya("com.ximalaya.ting.android"),
    wechat("com.tencent.mm"),
    qq("com.tencent.mobileqq"),
    qqmusic("com.tencent.qqmusic"),
    weread("com.tencent.weread"),
    qqreader("com.qq.reader"),
    changba("com.changba"),
    cloudmusic("com.netease.cloudmusic"),
    dingding("com.alibaba.android.rimet"),
}